project:
  type: website
execute:
  freeze: auto
  
website:
  title: "**CLAUDE LYNCH**"
  favicon: assets/favicon2.png
  page-navigation: true
  back-to-top-navigation: true
  open-graph: true

# https://quarto.org/docs/websites/
  
  navbar:
    background: primary
    left:
        - text: ABOUT
          aria-label: "About Me"
          href: about.qmd
        - text: RESEARCH
          aria-label: "Research"
          href: research.qmd
        - text: PORTFOLIO
          aria-label: "Portfolio"
          href: portfolio.qmd      
        - text: CV
          aria-label: "CV"
          href: CV.qmd
        - text: QUIZZES
          aria-label: "Quizzes"
          href: quizzes.qmd

  page-footer:  

    right: 
      Made with [Quarto](https://quarto.org)


format:
  html:
    theme: pulse
    css: 
    - styles.css
    - https://cdn.rawgit.com/jpswalsh/academicons/master/css/academicons.min.css

    toc: true

editor: visual

