project:
  type: website
execute:
  freeze: auto
  
website:
  title: "Claude Lynch"
  favicon: assets/favicon2.png
  page-navigation: true
  back-to-top-navigation: true
  open-graph: true

# https://quarto.org/docs/websites/
  
  navbar:
    background: danger
    left:
        - text: About
          aria-label: "About Me"
          href: about.qmd
        - text: Research
          aria-label: "Research"
          href: research.qmd
        - text: Portfolio
          aria-label: "Portfolio"
          href: portfolio.qmd      
        - text: CV
          aria-label: "CV"
          href: CV.qmd


  page-footer:  

    right: 
      Made with [Quarto](https://quarto.org)


format:
  html:
    theme: cosmo
    css: 
    - styles.css
    - https://cdn.rawgit.com/jpswalsh/academicons/master/css/academicons.min.css

    toc: true

editor: visual

