---
title: ""
subtitle: ""
---

## PhD study {#sec-phd}

I'm accepting PhD applicants on topics using geographic information systems and/or Earth observation including:

-   City sustainability
-   Safety in the built environment
-   Urban design and mental well-being
-   Applications of accessibility and transport networks (using new tools such as R5R)
-   Environmental / social / political equity (e.g. urban heat islands and redlining)
-   Applied urban research using big spatial data tools (e.g. DuckDB, PostGIS or Google Earth Engine)

### Current students

Emmanuel Farinre “The Mental Health of Individuals and Neighbourhoods & Victims and Perpetrators of Violence. Where do we Intervene”.

### Completed students

Dr Matthew Ng “Analysing Urban Growth in Brunei: a focus on land-use, accessibility, and policy”.

## MSc/MRes study

I'm the MSc/MRes Urban Spatial Science programme leader. The programme equips students with a multi-disciplinary and critical perspective on approaches to understanding, monitoring and improving global urban resilience and sustainability through the use of data. Taught content explores the theoretical, social and scientific foundations of the modern built environment through a geo-spatial, data-oriented lens. [Learn more about the MSc/MRes Urban Spatial Science →](https://www.ucl.ac.uk/bartlett/casa/study/urban-spatial-science-msc){.subtitle}

### Past students

|  |  |  |  |
|----------------|--------------------------|----------------|----------------|
| Student | Research | GitHub | Award |
| Yi-Chien Chen | Exploring the distribution of town centre accessibility through sustainable modes; A data-informed approach to London’s sustainable transport strategy | [{{< fa brands github >}}](https://github.com/yichienchen99/CASA0010_dissertation) |  |
| Lorena Brambila Cantu | A gendered approach to understanding pedestrians’ perception of safety and the built environment; A case study of London | [{{< fa brands github >}}](https://github.com/lorebram/pedestrian-percieved-safety) |  |
| Loubna Sasso | Exploring areas of upgrade based on the 15-minute city concept – A case study of London | [{{< fa brands github >}}](https://github.com/LoubnaSasso/CASA-Dissertation_LS) | 2022 Society For Location Analysis Masters Award |
| Signe Swarttouw | Exploring the distribution of urban building carbon emissions; A spatial approach to Westminster's decarbonisation strategy | [{{< fa brands github >}}](https://github.com/signesw/CASA0010_Dissertation) | 2021 Royal Geographical Society Planning and Environment |
| Cheyne Campbell | Taking Steps Towards Pedestrian Safety: A Case Study of Charlotte, North Carolina | [{{< fa brands github >}}](https://github.com/cheynecampbell/charlotte-pedestrian-safety) | 2020 Royal Geographical Society Planning and Environment |

## Scholarships

I apply and maintain a range of scholarship funding for our MSc, including:

-   [Office for Students Conversion Course funding (CASA Urban Futures)](https://www.ucl.ac.uk/bartlett/casa/study/scholarships/casa-urban-futures-masters-scholarships)
-   [Commonwealth Shared Scholarship Scheme](https://www.ucl.ac.uk/scholarships/commonwealth-shared-scholarship-scheme)
